### ISSUE TITLE
Need bug fix from gatsby in order to use cached Nodes.

### ISSUE THREAD

**Issue by tbaustin** [escaladesports/gatsby-source-salsify#1]
https://github.com/gatsbyjs/gatsby/issues/6968

Everything is logging out correctly, but it seems that the nodes need to be created in order to be referenced by the cache (fileNodeID), which completely defeats the purpose of caching them. 

This may not be a viable option even with this fix due to build time. This seems to be a common issue with the `gatsby-source-wordpress`. Here is an example issue https://github.com/gatsbyjs/gatsby/issues/4293

**Comment by kennedyrose** [comment]
Stale
